import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link  from 'next/link'

export default function Home() {
  return (
    <>
      <Head>
        <title>Elite Coder</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        

      </Head>

    {/* Show Blog post */}
    <div className="container mt-4">
     
        <div className="row">
        <div
  className="card shadow p-3 mb-5 bg-white rounded "
  style={{ width: "100%" }}
>
  <h5 className="card-header bg-white">Author Sumit</h5>
  <div className="card-body">
    <h5 className="card-title">Introduction To Computer Network</h5>
    <pre className="card-text text-dark">
      1) Introduction{"\n"}2) Client-server architecture{"\n"}3) Protocols{"\n"}
      4) How data is Transferred
    </pre>
    <Link href="/blogpost/This is java cource">  
      <a className="btn btn-primary">Read more</a>
      
     </Link>
   
  </div>
</div>

        </div>
    </div>
    {/* End Show Blog post */}
      
   
    </>
  )
}
